export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_DEFECTS_SUCCESS = 'FETCH_DEFECTS_SUCCESS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_DEFECT = 'ADD_DEFECT';
export const RESOLVE_DEFECT = 'RESOLVE_DEFECT';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';